### ISSUE TITLE
Add support for Asterisk > 14 ARI "channelvars" support in ws events

### ISSUE THREAD

**Issue by ivlovric** [CyCoreSystems/ari-proxy#18]
example of event:
< {
  "type": "Dial",
  "timestamp": "2018-04-21T18:48:30.969+0200",
  "dialstatus": "",
  "forward": "",
  "dialstring": "100",
  "peer": {
    "id": "1",
    "name": "SIP/100-00000001",
    "state": "Down",
    "caller": {
      "name": "Joe User 100",
      "number": "000000"
    },
    "connected": {
      "name": "",
      "number": "000000"
    },
    "accountcode": "",
    "dialplan": {
      "context": "local",
      "exten": "",
      "priority": 1
    },
    "creationtime": "2018-04-21T18:48:30.968+0200",
    "language": "en",
    "channelvars": {
      "foo": "foovariabletest",
      "bar": "barvariabletest"
    }
  },

Channelvars with variables foo ad bar are not parsed in ari-proxy.

EDIT:
more info
https://issues.asterisk.org/jira/browse/ASTERISK-26492

Thanks

**Comment by Ulexus** [comment]
Ah, nice.  Thanks for the information.  I'll see if I can get that pulled in.

**Comment by ivlovric** [comment]
Great, thanks.
attached you can find websocket data with one simulated call where subscriptions are set to all ARI events.
[ARI-events-one call-channelvars.txt](https://github.com/CyCoreSystems/ari-proxy/files/1935738/ARI-events-one.call-channelvars.txt)

**Comment by Ulexus** [comment]
v2.1.6 pulls in ARI library version v4.6.0, which adds support for ChannelVars on ChannelData.

**Comment by ivlovric** [comment]
Thank you.
I am just wondering why I still cant see these variables proxied by ari-proxy after the update.
Pulled ARI library is updated to version 4.6.0 as well.

This is what I got as an example from one ws message:

> DBUG[04-22|01:50:41] event received                           kind=ChannelCreated
> DBUG[04-22|01:50:41] listening for events                     application=local-call
> DBUG[04-22|01:50:41] event received                           kind=ChannelVarset
> DBUG[04-22|01:50:41] listening for events                     application=local-call
> DBUG[04-22|01:50:41] event received                           kind=ChannelDialplan
> DBUG[04-22|01:50:41] listening for events                     application=local-call
> [TRACE] <-- MSG ari.event.local-call.00:0c:29:38:ca:a7 2 358
> {"application":"local-call","asterisk_id":"00:0c:29:38:ca:a7","timestamp":"2018-04-22T01:50:41.645+0200","type":"ChannelCreated","channel":{"id":"1","name":"SIP/100-0000000b","state":"Down","accountcode":"","caller":{"name":"Joe User 100"},"connected":{},"creationtime":"2018-04-21T23:50:41.645+0000","dialplan":{"context":"local","exten":"s","priority":1}}}"

No channelvars present in any message from ari-proxy.

**Comment by Ulexus** [comment]
Sorry; because I'm an idiot.  Give me a moment.

**Comment by ivlovric** [comment]
Thank you for your great support. Looks good so far.

> [TRACE] <-- MSG ari.event.local-call.00:0c:29:38:ca:a7 2 422
> {"application":"local-call","asterisk_id":"00:0c:29:38:ca:a7","timestamp":"2018-04-22T02:36:55.346+0200","type":"ChannelCreated","channel":{"id":"1","name":"SIP/100-00000010","state":"Down","accountcode":"","caller":{"name":"Joe User 100"},"connected":{},"creationtime":"2018-04-22T00:36:55.346+0000","dialplan":{"context":"local","exten":"s","priority":1},"channelvars":{"bar":"barvariabletest","foo":"foovariabletest"}}}

**Comment by Ulexus** [comment]
Thanks!  Let me know if you encounter further problems.  I don't anticipate anything.
