### ISSUE TITLE
Library broken?

### ISSUE THREAD

**Issue by mtryfoss** [CyCoreSystems/ari-proxy#24]
./github.com/CyCoreSystems/ari-proxy/client/bridge.go:25:28: cannot use b (type *bridge) as type ari.Bridge in argument to ari.NewBridgeHandle:
    ,*bridge does not implement ari.Bridge (missing AddChannelWithOptions method)

If you checkout commit 0b99272cec6482252f0f578329fcc197cb54cee2 or ari-lib it still works, but not any newer.

**Comment by Ulexus** [comment]
This sounds like you are using the master branch of ARI rather than the latest versioned branch.  There is presently API breakage between master and the released branch.

How are you pulling your dependencies?

**Comment by mtryfoss** [comment]
Yes, probably. No problem. Just wanted to let you know.
I just imported the package in the go script, and ran "go get".

**Comment by Ulexus** [comment]
I have pushed an update to master which should be in sync with ari's master.  I really just need to finish up the version bump on ari...
