### ISSUE TITLE
Asterisk down, but ari-proxy is still running

### ISSUE THREAD

**Issue by mtryfoss** [CyCoreSystems/ari-proxy#25]
Normally not an issue, but if this happens the ari-proxy will consume for example originate commands not destined for a specific Asterisk server from NATS and they will fail.

Should there be some kind of temp unsubscribe feature in ari-proxy against NATS if the connection towards Asterisk is down?

**Comment by Ulexus** [comment]
That sounds like an excellent idea, yes.  Feel free to PR the mod or I'll take a stab at it in a few days.

**Comment by mtryfoss** [comment]
My knowledge of this component is still at the "use, not develop"-stage :) 
So I've got no proposal for this yet. But I'd be happy to test.

**Comment by Ulexus** [comment]
No problem at all; I just like to give people the opportunity.  I'll see if I can tackle this over the weekend.

**Comment by mtryfoss** [comment]
Thank you! Absolutely no hurry. Have a nice weekend!
