### ISSUE TITLE
Issue with Asterisk node-id

### ISSUE THREAD

**Issue by mtryfoss** [CyCoreSystems/ari-proxy#31]
Hello,

We've got Asterisk running on a server where two physical interfaces are bonded. The bonding driver picks one of the physical adapters MAC-address.

I did some maintenance which caused a quick down/up of the interface. For some reason the other MAC-address was then selected.
ari-proxy was running through the process.

After this all calls stopped working, and looking at NATS-traces it's pretty clear what happens:

PUB ari.announce 57.
{"node":"ac:1f:6b:76:7a:ba","application":"mobile_stage"}. <- old mac used in announce

MSG ari.event.mobile_stage.ac:1f:6b:76:7a:ba 2 615. <- old mac used for subject string
{"application":"mobile_stage","asterisk_id":"ac:1f:6b:76:7a:bb" <- new mac used in the actual event

This is a corner case, but I thought would let you know.

Maybe we could add some check to the function publishing StasisStart and see if asterisk_id has been changed and then maybe reinitialize everything?

**Comment by Ulexus** [comment]
That sounds like a good idea to me, yes.

**Comment by mtryfoss** [comment]
I've created a pull request for this one, but there might be better approaches. Another is to simply exit and let systemd or similar start a clean client.

It's also dependent on a change (bugfix) on the ari client for the connection to get marked as connected again.

**Comment by mtryfoss** [comment]
Closing this one.
